WEBUI.LANG["ta"] = {};


//Common
WEBUI.LANG["ta"]["Logout"] = "வெளியேறு";
WEBUI.LANG["ta"]["Name"] = "பெயர்";
WEBUI.LANG["ta"]["Name*"] = "பெயர்<span style='color:red;'>*</span>";
WEBUI.LANG["ta"]["Phone"] = "மொபைல்";
WEBUI.LANG["ta"]["New"] = "புதிது";
WEBUI.LANG["ta"]["Save"] = "சேமி";
WEBUI.LANG["ta"]["Remove"] = "நீக்கு";
WEBUI.LANG["ta"]["Search"] = "தேடு";
WEBUI.LANG["ta"]["Searching"] = "தேடுகிறது....";
WEBUI.LANG["ta"]["ID"] = "ஐடி";
WEBUI.LANG["ta"]["DATE:"] = "தேதி:";
WEBUI.LANG["ta"]["TIME:"] = "நேரம்:";
WEBUI.LANG["ta"]["SNo"] = "வஎண்";
WEBUI.LANG["ta"]["Phone No"] = "தொலைபேசி எண்";
WEBUI.LANG["ta"]["Address"] = "முகவரி";
WEBUI.LANG["ta"]["Mobile no"] = "அலைபேசி எண்";
WEBUI.LANG["ta"]["Mobile No*"] = "மொபைல் எண்<span style='color:red;'>*</span>";
WEBUI.LANG["ta"]["Landline no"] = "லாண்ட்லைன் எண்";
WEBUI.LANG["ta"]["Email"] = "மின்னஞ்சல்";
WEBUI.LANG["ta"]["Created Date"] = "உருவாக்கிய தேதி";
WEBUI.LANG["ta"]["Active"] = "செயலில்";
WEBUI.LANG["ta"]["Area"] = "இடம்";
WEBUI.LANG["ta"]["Bank Name"] = "வங்கி பெயர்";
WEBUI.LANG["ta"]["Bank Details"] = "வங்கி விவரங்கள்";
WEBUI.LANG["ta"]["Account No"] = "வ.கணக்கு எண்";
WEBUI.LANG["ta"]["Account Number"] = "வ.கணக்கு எண்";
WEBUI.LANG["ta"]["IFSC Code"] = "IFSC கோடு";
WEBUI.LANG["ta"]["TIN No"] = "டின் எண்";
WEBUI.LANG["ta"]["D.LNo"] = "டி.எல் எண்";
WEBUI.LANG["ta"]["Sl No"] = "வரிசை எண்";
WEBUI.LANG["ta"]["GST No"] = "ஜிஎஸ்டி எண்";
WEBUI.LANG["ta"]["Bill No"] = "பில் எண்";
WEBUI.LANG["ta"]["Bill No:"] = "பில் எண்:";
WEBUI.LANG["ta"]["Bill Date"] = "பில் தேதி";
WEBUI.LANG["ta"]["Expense Name"] = "செலவு பெயர்";
WEBUI.LANG["ta"]["Expense Amount"] = "செலவு மொத்தம்";
WEBUI.LANG["ta"]["Sub Total"] = "கூட்டுத்தொகை";
WEBUI.LANG["ta"]["Sub Total:"] = "கூட்டுத்தொகை:";
WEBUI.LANG["ta"]["Round Off"] = "முழுதாக்கல்";
WEBUI.LANG["ta"]["Total"] = "மொத்தம்";
WEBUI.LANG["ta"]["Enter Bill No"] = "பில் எண் உள்ளிடவும்";
WEBUI.LANG["ta"]["Back"] = "பின்னால்";
WEBUI.LANG["ta"]["Print"] = "அச்சு";
WEBUI.LANG["ta"]["Start Date"] = "தொடக்க தேதி";
WEBUI.LANG["ta"]["End Date"] = "கடைசி தேதி";
WEBUI.LANG["ta"]["Advance Name"] = "அட்வான்ஸ் பெயர்";
WEBUI.LANG["ta"]["Advance End Date"] = "அட்வான்ஸ் முடிவு தேதி";
WEBUI.LANG["ta"]["Advance Amount"] = "அட்வான்ஸ் தொகை";
WEBUI.LANG["ta"]["Enter Name, ID, Phone no"] = "பெயர், ஐடி அல்லது தொலைபேசி எண் உள்ளிடவும்";
WEBUI.LANG["ta"]["Company Name"] = "கம்பேனி பெயர்";
WEBUI.LANG["ta"]["Company Id"] = "கம்பேனி ஐடி";
WEBUI.LANG["ta"]["Date Of Birth"] = "பிறந்த தேதி";
WEBUI.LANG["ta"]["Status"] = "நிலைமை";
WEBUI.LANG["ta"]["Reward Plans"] = "வெகுமதி திட்டங்கள்";
WEBUI.LANG["ta"]["Points"] = "புள்ளிகள்";
WEBUI.LANG["ta"]["PAN No"] = "பான் எண்";
WEBUI.LANG["ta"]["Aadhaar No"] = "ஆதார் எண்";
WEBUI.LANG["ta"]["Aadhaar No*"] = "ஆதார் எண்<span style='color:red;'>*</span>";
WEBUI.LANG["ta"]["F1 - New"] = "F1 - புதிது";
WEBUI.LANG["ta"]["F2 - Save"] = "F2 - சேமி";
WEBUI.LANG["ta"]["Ctrl + R - Remove"] = "Ctrl + R - நீக்கு";
WEBUI.LANG["ta"]["Ctrl + P - Print"] = "Ctrl + P - அச்சிடு";
WEBUI.LANG["ta"]["Report"] = "அறிக்கை";
WEBUI.LANG["ta"]["Address Line"] = "முகவரி வரி";
WEBUI.LANG["ta"]["Street"] = "தெரு";
WEBUI.LANG["ta"]["Pincode"] = "அஞ்சல் குறியீடு";
WEBUI.LANG["ta"]["Export Type"] = "வகை";
WEBUI.LANG["ta"]["Go"] = "எடு";
WEBUI.LANG["ta"]["Payment Type"] = "கட்டணம் வகை";
WEBUI.LANG["ta"]["Invoice No"] = "விலைப்பட்டியல் எண்";
WEBUI.LANG["ta"]["Invoice No *"] = "விலைப்பட்டியல் எண் *";
WEBUI.LANG["ta"]["Transaction Date"] = "பரிவர்த்தனை தேதி";
WEBUI.LANG["ta"]["No"] = "எண்";
WEBUI.LANG["ta"]["Rate"] = "விலை";
WEBUI.LANG["ta"]["**  THANK YOU VISIT AGAIN  **"] = "** நன்றி மீண்டும் வருக **";
WEBUI.LANG["ta"]["Send SMS"] = "SMS அனுப்பவும்";
WEBUI.LANG["ta"]["Send Email"] = "மின்னஞ்சல் அனுப்பு";
WEBUI.LANG["ta"]["More"] = "மேலும்";
WEBUI.LANG["ta"]["Less"] = "குறை";
WEBUI.LANG["ta"]["City"] = "சிட்டி";
WEBUI.LANG["ta"]["State"] = "மாநிலம்";
WEBUI.LANG["ta"]["Mobile"] = "மொபைல்";
WEBUI.LANG["ta"]["Personal Details"] = "தனிப்பட்ட விபரம்";
WEBUI.LANG["ta"]["Mobile No"] = "மொபைல் எண்";
WEBUI.LANG["ta"]["Alternate Mobile No"] = "மாற்று மொபைல் எண்";
WEBUI.LANG["ta"]["Photo"] = "புகைப்படம்";
WEBUI.LANG["ta"]["Upload Photo"] = "பதிவேற்றம் செய்க";


//Staff Screen Start
WEBUI.LANG["ta"]["Enter staff id or name"] = "ஊழியர்கள் ஐடி அல்லது பெயரை உள்ளிடவும்";
WEBUI.LANG["ta"]["Staff name is mandatory ...!"] = "ஊழியர் பெயரை உள்ளிடவும்...!";
WEBUI.LANG["ta"]["Mobile no is mandatory ...!"] = "மொபைல் எண்ணை உள்ளிடவும்...!";
WEBUI.LANG["ta"]["Aadhar no is mandatory ...!"] = "ஆதார் எண்ணை உள்ளிடவும்";
WEBUI.LANG["ta"]["Inserting new staff..."] = "புதிய ஊழியரை சேமிக்கிறது....!";
WEBUI.LANG["ta"]["New Staff saved successfully...!"] = "புதிய ஊழியரின் தகவல் சேமிக்கப்பட்டது....!";
WEBUI.LANG["ta"]["Updating new staff..."] = "ஊழியரின் தகவல்களை சேமிக்கிறது....!";
WEBUI.LANG["ta"]["Staff updated successfully...!"] = "ஊழியரின் தகவல் சேமிக்கப்பட்டது....!";
WEBUI.LANG["ta"]["Select a staff first...!"] = "முதலில் ஊழியரை தேர்வு செய்யவும்....!";
WEBUI.LANG["ta"]["Are You Sure Want To Remove This Staff If You Delete This Staff The Details Cannot Be Retrived"] = "ஊழியரை நீக்குவதை மறுபடியும் தேர்வு செய்க, ஒருமுறை நீக்கினால் தகவல்களை திரும்ப பெற இயலாது"
WEBUI.LANG["ta"]["Staff removed successfully...!"] = "ஊழியரின் தகவல் நீக்கப்பட்டுவிட்டது....!";
//Staff Screen End